### ISSUE TITLE
`install_from` and `channel_name` metrics are null strings when doing query

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxRealityPC#202]
**Environment (please complete the following information):**
The telemetry result from [FxR dashboard](https://sql.telemetry.mozilla.org/dashboard/firefox-reality-pc).

**Describe the bug**
I checked our call stack, we do set proper values into Glean via its interfaces. and the [Ping debug viewer](https://debug-ping-preview.firebaseapp.com/pings/dmu) also tells us our metrics string are
```
"metrics": {"string":{"distribution.ff_install_from":"embedded",
"distribution.fxr_channel_name":"htc",
"launch.entry_method":"library"}}
```

According to our [ManualMetric](https://github.com/MozillaReality/FirefoxRealityPC/blob/26d2e6a85a69adaf60491e88bd9cd5219012af4a/Source/FirefoxRealityUnity/Assets/Scripts/FxRManualMetrics.cs#L27-L51), our metric name matches to the string we saw in [Ping debug viewer](https://debug-ping-preview.firebaseapp.com/pings/dmu).

However, when querying the metric of `distribution.fxr_channel_name` from our data table (https://sql.telemetry.mozilla.org/queries/75451/source#188352), it tells us we don't have this type in the structure, and it suggests us using `channel_name`. But, using `channel_name`, we are only able to see a null string.

**To Reproduce**
1. Check the query result from the telemetry result from [FxR dashboard](https://sql.telemetry.mozilla.org/dashboard/firefox-reality-pc).

**Expected behavior**
The `install_from` should be `embedded`, and `channel_name` should be `htc`.

**Comment by daoshengmu** [comment]
@Dexterp37 Do you have ideas why I get `null` strings when doing query? It looks like there is something in the struct of our table.

**Comment by Dexterp37** [comment]
@daoshengmu hey! The reason why you're not seeing data in tables is that there's a mismatch between the metrics category/names as declared in the [`ManualMetrics.cs`](https://github.com/MozillaReality/FirefoxRealityPC/blob/26d2e6a85a69adaf60491e88bd9cd5219012af4a/Source/FirefoxRealityUnity/Assets/Scripts/FxRManualMetrics.cs#L31) and the [official registry files](https://github.com/MozillaReality/FirefoxRealityPC/blob/26d2e6a85a69adaf60491e88bd9cd5219012af4a/Source/FirefoxRealityUnity/metrics.yaml#L9).

They should always match, otherwise you'll end up with unknown columns/nulls. Since data was sent with the names / categories from the Manualmetrics file, you should change `metrics.yaml` to match what's in that file. Ideally, you'd want to update to the most recent version of Glean supported in C# that has automatic code generation. But manually changing the registry file, given the state of this product, is probably the best option.

I'm happy to review as needed.

After the changes get merged, you'll see the data in the columns the following day, I think.
